global using System.Globalization;
global using System.Net;
global using System.Text.Json;
global using Microsoft.AspNetCore.Mvc;
global using AutoMapper;
global using CRUD.WebAPI.NET6.Entities;
global using CRUD.WebAPI.NET6.Helpers;
global using CRUD.WebAPI.NET6.Models.Users;
global using CRUD.WebAPI.NET6.Services;